# Generated by Django 5.2.7 on 2025-11-30 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_instituciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Orientacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Orientación',
                'verbose_name_plural': 'Orientaciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Código único de la comisión (Ej: 2024-LP-01)', max_length=50)),
                ('horario', models.CharField(help_text='Días y horarios', max_length=100)),
                ('turno', models.CharField(choices=[('M', 'Mañana'), ('T', 'Tarde'), ('V', 'Vespertino'), ('N', 'Noche')], max_length=1)),
                ('tutor', models.CharField(blank=True, max_length=200, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='comisiones', to='gestion_instituciones.sede')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='comisiones', to='gestion_comisiones.modulo')),
                ('orientacion', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='comisiones', to='gestion_comisiones.orientacion')),
            ],
            options={
                'verbose_name': 'Comisión',
                'verbose_name_plural': 'Comisiones',
                'ordering': ['numero'],
            },
        ),
    ]
