"""
Django settings for fines_heat_map project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv
from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

# Cargar variables de entorno
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-bxs-1kt2zb$&l%wtk0z)-&#-nrrcbxq9f63zz13797czi5r0jh"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["127.0.0.1", "localhost", "192.168.1.33", "192.168.0.156"]


# Application definition

INSTALLED_APPS = [
    "unfold",  # Debe ir ANTES de django.contrib.admin
    "unfold.contrib.filters",  # Filtros mejorados
    "unfold.contrib.forms",  # Formularios mejorados
    "unfold.contrib.import_export",  # Integración con django-import-export
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'import_export',
    "rest_framework",
    "fines_heat_map.apps.FinesHeatMapConfig",  # AppConfig para inicializar el admin
    "heatmap",
    "gestion_instituciones.apps.GestionInstitucionesConfig",
    "gestion_comisiones.apps.GestionComisionesConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "fines_heat_map.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "fines_heat_map.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


# configuracion de la base de datos en PostgreSQL (alojado en NeonTech) usando la libreria dj_database_url
DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get('DATABASE_URL'),
        conn_max_age=600,
        ssl_require=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "es-AR"

TIME_ZONE = "America/Argentina/Buenos_Aires"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ==================================================
# CONFIGURACIÓN DE DJANGO-UNFOLD
# ==================================================

def environment_callback(request):
    return "Development" if DEBUG else "Production"

UNFOLD = {
    "SITE_TITLE": _("FinEs Mapa Interactivo"),
    "SITE_HEADER": _("Panel de Administración"),
    "SITE_URL": "/",
    "SITE_ICON": lambda request: static("img/texto_transparente.png"),
    "SITE_LOGO": lambda request: static("img/texto_transparente.png"),
    "SITE_SYMBOL": "settings",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "ENVIRONMENT": "fines_heat_map.settings.environment_callback",
    "DASHBOARD_CALLBACK": None,  # Usamos nuestro propio custom_index en admin_init.py
    "LOGIN": {
        "image": lambda request: static("img/texto_transparente.png"),
        "redirect_after": lambda request: reverse_lazy("admin:index"),
    },
    "STYLES": [],
    "SCRIPTS": [],
    "COLORS": {
        "primary": {
            "50": "245 245 255",
            "100": "235 235 255",
            "200": "220 220 255",
            "300": "200 200 255",
            "400": "170 170 255",
            "500": "36 36 235",  # #2424eb
            "600": "26 26 180",
            "700": "20 20 150",
            "800": "15 15 120",
            "900": "10 10 90",
            "950": "5 5 50",
        },
    },
    "EXTENSIONS": {
        "modeltranslation": {
            "flags": {
                "en": "🇬🇧",
                "fr": "🇫🇷",
                "nl": "🇳🇱",
            },
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
    },
}

# ==================================================
# CONFIGURACIÓN PERSONALIZADA DEL PROYECTO FINES
# ==================================================

# Configuración del mapa interactivo
MAP_CONFIG = {
    "default_center": [-34.9214, -57.9544],  # La Plata, Argentina
    "default_zoom": 12,
    "max_zoom": 18,
    "min_zoom": 6,
    "heatmap_radius": 225,
    "cluster_max_zoom": 15,
}

# Datos de ejemplo para desarrollo (reemplazar con modelos reales)
EXAMPLE_PLACES = [
    {
        "id": 1,
        "name": "Escuela Media N°3",
        "commission_number": "101",
        "city": "La Plata",
        "province": "Buenos Aires",
        "turno": "Noche",
        "address": "Av. 7 y 60",
        "lat": -34.9215,
        "lng": -57.9545,
        "modules": ["Matemática", "Lengua"],
        "orientation": "Ciencias Sociales",
    },
    {
        "id": 2,
        "name": "Centro Comunitario El Sol",
        "commission_number": "102",
        "city": "La Plata",
        "province": "Buenos Aires",
        "turno": "Tarde",
        "address": "Calle 12 y 50",
        "lat": -34.9105,
        "lng": -57.9435,
        "modules": ["Biología", "Química"],
        "orientation": "Ciencias Naturales",
    },
    {
        "id": 3,
        "name": "Instituto Técnico Industrial",
        "commission_number": "103",
        "city": "Mar del Plata",
        "province": "Buenos Aires",
        "turno": "Mañana",
        "address": "Av. Constitución 1234",
        "lat": -38.0055,
        "lng": -57.5426,
        "modules": ["Tecnología", "Matemática"],
        "orientation": "Técnica",
    },
]
